import numpy as np
from scipy.spatial import KDTree
from typing import Dict, List, Union, Callable, Tuple, Optional, Any
from sklearn.metrics import r2_score
from .numpy_extra import sample_line_segment
import open3d as o3d
from tqdm import tqdm
import os
from datetime import datetime
import traceback
from .xlsx_io import write_dicts_to_xlsx

_synthetic_tree_files_with_selected: List[Tuple[str, bool]] = [
    ('apple/apple_1.npz', False),
    ('apple/apple_2.npz', False),
    ('apple/apple_3.npz', False),
    ('apple/apple_4.npz', False),
    ('apple/apple_5.npz', False),
    ('apple/apple_6.npz', False),
    ('apple/apple_7.npz', False),
    ('apple/apple_8.npz', False),
    ('apple/apple_9.npz', False),
    ('apple/apple_10.npz', False),
    ('apple/apple_11.npz', False),
    ('apple/apple_12.npz', True),
    ('apple/apple_13.npz', False),
    ('apple/apple_14.npz', False),
    ('apple/apple_15.npz', False),
    ('apple/apple_16.npz', True),
    ('apple/apple_17.npz', False),
    ('apple/apple_18.npz', False),
    ('apple/apple_19.npz', False),
    ('apple/apple_20.npz', False),
    ('apple/apple_21.npz', False),
    ('apple/apple_22.npz', False),
    ('apple/apple_23.npz', True),
    ('apple/apple_24.npz', False),
    ('apple/apple_25.npz', False),
    ('apple/apple_26.npz', False),
    ('apple/apple_27.npz', False),
    ('apple/apple_28.npz', False),
    ('apple/apple_29.npz', False),
    ('apple/apple_30.npz', False),
    ('apple/apple_31.npz', False),
    ('apple/apple_32.npz', False),
    ('apple/apple_33.npz', False),
    ('apple/apple_34.npz', False),
    ('apple/apple_35.npz', False),
    ('apple/apple_36.npz', True),
    ('apple/apple_37.npz', False),
    ('apple/apple_38.npz', False),
    ('apple/apple_39.npz', False),
    ('apple/apple_40.npz', False),
    ('apple/apple_41.npz', False),
    ('apple/apple_42.npz', False),
    ('apple/apple_43.npz', False),
    ('apple/apple_44.npz', False),
    ('apple/apple_45.npz', False),
    ('apple/apple_46.npz', False),
    ('apple/apple_47.npz', False),
    ('apple/apple_48.npz', False),
    ('apple/apple_49.npz', False),
    ('apple/apple_50.npz', False),
    ('apple/apple_51.npz', False),
    ('apple/apple_52.npz', False),
    ('apple/apple_53.npz', True),
    ('apple/apple_54.npz', False),
    ('apple/apple_55.npz', False),
    ('apple/apple_56.npz', False),
    ('apple/apple_57.npz', False),
    ('apple/apple_58.npz', False),
    ('apple/apple_59.npz', False),
    ('apple/apple_60.npz', False),
    ('apple/apple_61.npz', False),
    ('apple/apple_62.npz', False),
    ('apple/apple_63.npz', True),
    ('apple/apple_64.npz', False),
    ('apple/apple_65.npz', False),
    ('apple/apple_66.npz', False),
    ('apple/apple_67.npz', False),
    ('apple/apple_68.npz', False),
    ('apple/apple_69.npz', False),
    ('apple/apple_70.npz', False),
    ('apple/apple_71.npz', False),
    ('apple/apple_72.npz', False),
    ('apple/apple_73.npz', False),
    ('apple/apple_74.npz', False),
    ('apple/apple_75.npz', False),
    ('apple/apple_76.npz', False),
    ('apple/apple_77.npz', False),
    ('apple/apple_78.npz', False),
    ('apple/apple_79.npz', False),
    ('apple/apple_80.npz', False),
    ('apple/apple_81.npz', False),
    ('apple/apple_82.npz', False),
    ('apple/apple_83.npz', True),
    ('apple/apple_84.npz', False),
    ('apple/apple_85.npz', False),
    ('apple/apple_86.npz', True),
    ('apple/apple_87.npz', False),
    ('apple/apple_88.npz', False),
    ('apple/apple_89.npz', False),
    ('apple/apple_90.npz', False),
    ('apple/apple_91.npz', False),
    ('apple/apple_92.npz', True),
    ('apple/apple_93.npz', False),
    ('apple/apple_94.npz', False),
    ('apple/apple_95.npz', False),
    ('apple/apple_96.npz', False),
    ('apple/apple_97.npz', True),
    ('apple/apple_98.npz', False),
    ('apple/apple_99.npz', False),
    ('apple/apple_100.npz', False),
    ('cherry/cherry_1.npz', False),
    ('cherry/cherry_2.npz', False),
    ('cherry/cherry_3.npz', False),
    ('cherry/cherry_4.npz', True),
    ('cherry/cherry_5.npz', False),
    ('cherry/cherry_6.npz', False),
    ('cherry/cherry_7.npz', False),
    ('cherry/cherry_8.npz', False),
    ('cherry/cherry_9.npz', False),
    ('cherry/cherry_10.npz', False),
    ('cherry/cherry_11.npz', False),
    ('cherry/cherry_12.npz', False),
    ('cherry/cherry_13.npz', False),
    ('cherry/cherry_14.npz', False),
    ('cherry/cherry_15.npz', True),
    ('cherry/cherry_16.npz', False),
    ('cherry/cherry_18.npz', False),
    ('cherry/cherry_19.npz', True),
    ('cherry/cherry_20.npz', False),
    ('cherry/cherry_22.npz', False),
    ('cherry/cherry_23.npz', False),
    ('cherry/cherry_24.npz', False),
    ('cherry/cherry_25.npz', False),
    ('cherry/cherry_26.npz', False),
    ('cherry/cherry_27.npz', False),
    ('cherry/cherry_28.npz', True),
    ('cherry/cherry_29.npz', False),
    ('cherry/cherry_30.npz', False),
    ('cherry/cherry_31.npz', False),
    ('cherry/cherry_32.npz', False),
    ('cherry/cherry_33.npz', False),
    ('cherry/cherry_34.npz', True),
    ('cherry/cherry_35.npz', False),
    ('cherry/cherry_36.npz', False),
    ('cherry/cherry_37.npz', False),
    ('cherry/cherry_38.npz', False),
    ('cherry/cherry_39.npz', False),
    ('cherry/cherry_40.npz', False),
    ('cherry/cherry_41.npz', False),
    ('cherry/cherry_42.npz', False),
    ('cherry/cherry_43.npz', False),
    ('cherry/cherry_44.npz', False),
    ('cherry/cherry_45.npz', False),
    ('cherry/cherry_46.npz', False),
    ('cherry/cherry_47.npz', False),
    ('cherry/cherry_48.npz', False),
    ('cherry/cherry_49.npz', True),
    ('cherry/cherry_50.npz', False),
    ('cherry/cherry_51.npz', False),
    ('cherry/cherry_52.npz', False),
    ('cherry/cherry_53.npz', False),
    ('cherry/cherry_54.npz', False),
    ('cherry/cherry_56.npz', True),
    ('cherry/cherry_57.npz', False),
    ('cherry/cherry_58.npz', False),
    ('cherry/cherry_59.npz', False),
    ('cherry/cherry_60.npz', False),
    ('cherry/cherry_61.npz', False),
    ('cherry/cherry_63.npz', False),
    ('cherry/cherry_64.npz', False),
    ('cherry/cherry_65.npz', False),
    ('cherry/cherry_66.npz', False),
    ('cherry/cherry_67.npz', False),
    ('cherry/cherry_68.npz', False),
    ('cherry/cherry_69.npz', False),
    ('cherry/cherry_70.npz', False),
    ('cherry/cherry_71.npz', False),
    ('cherry/cherry_72.npz', False),
    ('cherry/cherry_73.npz', False),
    ('cherry/cherry_74.npz', False),
    ('cherry/cherry_75.npz', True),
    ('cherry/cherry_76.npz', False),
    ('cherry/cherry_77.npz', False),
    ('cherry/cherry_78.npz', False),
    ('cherry/cherry_79.npz', False),
    ('cherry/cherry_80.npz', False),
    ('cherry/cherry_82.npz', True),
    ('cherry/cherry_83.npz', False),
    ('cherry/cherry_84.npz', False),
    ('cherry/cherry_85.npz', False),
    ('cherry/cherry_86.npz', False),
    ('cherry/cherry_87.npz', False),
    ('cherry/cherry_88.npz', False),
    ('cherry/cherry_89.npz', False),
    ('cherry/cherry_90.npz', True),
    ('cherry/cherry_91.npz', False),
    ('cherry/cherry_92.npz', False),
    ('cherry/cherry_93.npz', False),
    ('cherry/cherry_94.npz', False),
    ('cherry/cherry_95.npz', False),
    ('cherry/cherry_96.npz', False),
    ('cherry/cherry_97.npz', False),
    ('cherry/cherry_98.npz', False),
    ('cherry/cherry_99.npz', False),
    ('cherry/cherry_100.npz', False),
    ('eucalyptus/eucalyptus_1.npz', False),
    ('eucalyptus/eucalyptus_2.npz', False),
    ('eucalyptus/eucalyptus_4.npz', False),
    ('eucalyptus/eucalyptus_6.npz', False),
    ('eucalyptus/eucalyptus_7.npz', False),
    ('eucalyptus/eucalyptus_8.npz', False),
    ('eucalyptus/eucalyptus_9.npz', False),
    ('eucalyptus/eucalyptus_10.npz', False),
    ('eucalyptus/eucalyptus_11.npz', False),
    ('eucalyptus/eucalyptus_12.npz', False),
    ('eucalyptus/eucalyptus_13.npz', False),
    ('eucalyptus/eucalyptus_14.npz', False),
    ('eucalyptus/eucalyptus_15.npz', False),
    ('eucalyptus/eucalyptus_16.npz', False),
    ('eucalyptus/eucalyptus_17.npz', False),
    ('eucalyptus/eucalyptus_18.npz', False),
    ('eucalyptus/eucalyptus_19.npz', False),
    ('eucalyptus/eucalyptus_20.npz', False),
    ('eucalyptus/eucalyptus_21.npz', False),
    ('eucalyptus/eucalyptus_22.npz', False),
    ('eucalyptus/eucalyptus_23.npz', False),
    ('eucalyptus/eucalyptus_24.npz', False),
    ('eucalyptus/eucalyptus_25.npz', False),
    ('eucalyptus/eucalyptus_27.npz', False),
    ('eucalyptus/eucalyptus_28.npz', True),
    ('eucalyptus/eucalyptus_29.npz', False),
    ('eucalyptus/eucalyptus_30.npz', False),
    ('eucalyptus/eucalyptus_31.npz', False),
    ('eucalyptus/eucalyptus_32.npz', False),
    ('eucalyptus/eucalyptus_33.npz', False),
    ('eucalyptus/eucalyptus_34.npz', False),
    ('eucalyptus/eucalyptus_35.npz', True),
    ('eucalyptus/eucalyptus_36.npz', False),
    ('eucalyptus/eucalyptus_37.npz', False),
    ('eucalyptus/eucalyptus_38.npz', False),
    ('eucalyptus/eucalyptus_39.npz', False),
    ('eucalyptus/eucalyptus_40.npz', False),
    ('eucalyptus/eucalyptus_41.npz', False),
    ('eucalyptus/eucalyptus_42.npz', False),
    ('eucalyptus/eucalyptus_43.npz', False),
    ('eucalyptus/eucalyptus_44.npz', False),
    ('eucalyptus/eucalyptus_45.npz', False),
    ('eucalyptus/eucalyptus_46.npz', False),
    ('eucalyptus/eucalyptus_47.npz', False),
    ('eucalyptus/eucalyptus_49.npz', False),
    ('eucalyptus/eucalyptus_50.npz', False),
    ('eucalyptus/eucalyptus_51.npz', False),
    ('eucalyptus/eucalyptus_52.npz', False),
    ('eucalyptus/eucalyptus_53.npz', True),
    ('eucalyptus/eucalyptus_54.npz', True),
    ('eucalyptus/eucalyptus_55.npz', False),
    ('eucalyptus/eucalyptus_56.npz', False),
    ('eucalyptus/eucalyptus_57.npz', False),
    ('eucalyptus/eucalyptus_58.npz', True),
    ('eucalyptus/eucalyptus_59.npz', False),
    ('eucalyptus/eucalyptus_60.npz', False),
    ('eucalyptus/eucalyptus_61.npz', False),
    ('eucalyptus/eucalyptus_62.npz', False),
    ('eucalyptus/eucalyptus_63.npz', False),
    ('eucalyptus/eucalyptus_64.npz', False),
    ('eucalyptus/eucalyptus_65.npz', False),
    ('eucalyptus/eucalyptus_66.npz', False),
    ('eucalyptus/eucalyptus_67.npz', False),
    ('eucalyptus/eucalyptus_68.npz', False),
    ('eucalyptus/eucalyptus_69.npz', False),
    ('eucalyptus/eucalyptus_70.npz', True),
    ('eucalyptus/eucalyptus_71.npz', False),
    ('eucalyptus/eucalyptus_72.npz', False),
    ('eucalyptus/eucalyptus_73.npz', True),
    ('eucalyptus/eucalyptus_74.npz', False),
    ('eucalyptus/eucalyptus_75.npz', False),
    ('eucalyptus/eucalyptus_76.npz', False),
    ('eucalyptus/eucalyptus_77.npz', False),
    ('eucalyptus/eucalyptus_78.npz', False),
    ('eucalyptus/eucalyptus_79.npz', False),
    ('eucalyptus/eucalyptus_80.npz', False),
    ('eucalyptus/eucalyptus_82.npz', False),
    ('eucalyptus/eucalyptus_83.npz', False),
    ('eucalyptus/eucalyptus_84.npz', False),
    ('eucalyptus/eucalyptus_85.npz', False),
    ('eucalyptus/eucalyptus_86.npz', False),
    ('eucalyptus/eucalyptus_87.npz', False),
    ('eucalyptus/eucalyptus_88.npz', False),
    ('eucalyptus/eucalyptus_89.npz', True),
    ('eucalyptus/eucalyptus_90.npz', False),
    ('eucalyptus/eucalyptus_91.npz', False),
    ('eucalyptus/eucalyptus_92.npz', False),
    ('eucalyptus/eucalyptus_93.npz', False),
    ('eucalyptus/eucalyptus_94.npz', True),
    ('eucalyptus/eucalyptus_95.npz', False),
    ('eucalyptus/eucalyptus_96.npz', False),
    ('eucalyptus/eucalyptus_97.npz', False),
    ('eucalyptus/eucalyptus_98.npz', False),
    ('eucalyptus/eucalyptus_99.npz', False),
    ('eucalyptus/eucalyptus_100.npz', False),
    ('ginkgo/ginkgo_1.npz', False),
    ('ginkgo/ginkgo_2.npz', False),
    ('ginkgo/ginkgo_3.npz', False),
    ('ginkgo/ginkgo_4.npz', False),
    ('ginkgo/ginkgo_5.npz', False),
    ('ginkgo/ginkgo_7.npz', True),
    ('ginkgo/ginkgo_8.npz', False),
    ('ginkgo/ginkgo_9.npz', False),
    ('ginkgo/ginkgo_10.npz', False),
    ('ginkgo/ginkgo_11.npz', True),
    ('ginkgo/ginkgo_12.npz', False),
    ('ginkgo/ginkgo_13.npz', False),
    ('ginkgo/ginkgo_14.npz', False),
    ('ginkgo/ginkgo_15.npz', False),
    ('ginkgo/ginkgo_16.npz', False),
    ('ginkgo/ginkgo_17.npz', False),
    ('ginkgo/ginkgo_18.npz', True),
    ('ginkgo/ginkgo_19.npz', False),
    ('ginkgo/ginkgo_20.npz', False),
    ('ginkgo/ginkgo_21.npz', True),
    ('ginkgo/ginkgo_22.npz', False),
    ('ginkgo/ginkgo_23.npz', False),
    ('ginkgo/ginkgo_24.npz', False),
    ('ginkgo/ginkgo_25.npz', False),
    ('ginkgo/ginkgo_26.npz', False),
    ('ginkgo/ginkgo_27.npz', False),
    ('ginkgo/ginkgo_28.npz', False),
    ('ginkgo/ginkgo_29.npz', False),
    ('ginkgo/ginkgo_30.npz', False),
    ('ginkgo/ginkgo_31.npz', False),
    ('ginkgo/ginkgo_32.npz', False),
    ('ginkgo/ginkgo_33.npz', False),
    ('ginkgo/ginkgo_34.npz', False),
    ('ginkgo/ginkgo_35.npz', False),
    ('ginkgo/ginkgo_36.npz', False),
    ('ginkgo/ginkgo_37.npz', True),
    ('ginkgo/ginkgo_38.npz', False),
    ('ginkgo/ginkgo_39.npz', False),
    ('ginkgo/ginkgo_40.npz', False),
    ('ginkgo/ginkgo_41.npz', False),
    ('ginkgo/ginkgo_42.npz', False),
    ('ginkgo/ginkgo_43.npz', False),
    ('ginkgo/ginkgo_44.npz', False),
    ('ginkgo/ginkgo_45.npz', False),
    ('ginkgo/ginkgo_46.npz', False),
    ('ginkgo/ginkgo_47.npz', False),
    ('ginkgo/ginkgo_48.npz', False),
    ('ginkgo/ginkgo_49.npz', False),
    ('ginkgo/ginkgo_50.npz', False),
    ('ginkgo/ginkgo_51.npz', False),
    ('ginkgo/ginkgo_52.npz', False),
    ('ginkgo/ginkgo_53.npz', False),
    ('ginkgo/ginkgo_54.npz', False),
    ('ginkgo/ginkgo_55.npz', False),
    ('ginkgo/ginkgo_56.npz', False),
    ('ginkgo/ginkgo_57.npz', False),
    ('ginkgo/ginkgo_58.npz', False),
    ('ginkgo/ginkgo_59.npz', False),
    ('ginkgo/ginkgo_60.npz', False),
    ('ginkgo/ginkgo_61.npz', False),
    ('ginkgo/ginkgo_62.npz', False),
    ('ginkgo/ginkgo_63.npz', False),
    ('ginkgo/ginkgo_64.npz', False),
    ('ginkgo/ginkgo_65.npz', False),
    ('ginkgo/ginkgo_66.npz', False),
    ('ginkgo/ginkgo_67.npz', False),
    ('ginkgo/ginkgo_68.npz', False),
    ('ginkgo/ginkgo_69.npz', False),
    ('ginkgo/ginkgo_70.npz', False),
    ('ginkgo/ginkgo_71.npz', True),
    ('ginkgo/ginkgo_72.npz', False),
    ('ginkgo/ginkgo_73.npz', False),
    ('ginkgo/ginkgo_74.npz', False),
    ('ginkgo/ginkgo_75.npz', False),
    ('ginkgo/ginkgo_76.npz', False),
    ('ginkgo/ginkgo_77.npz', True),
    ('ginkgo/ginkgo_78.npz', False),
    ('ginkgo/ginkgo_79.npz', False),
    ('ginkgo/ginkgo_80.npz', False),
    ('ginkgo/ginkgo_81.npz', False),
    ('ginkgo/ginkgo_82.npz', False),
    ('ginkgo/ginkgo_83.npz', False),
    ('ginkgo/ginkgo_84.npz', False),
    ('ginkgo/ginkgo_85.npz', False),
    ('ginkgo/ginkgo_86.npz', False),
    ('ginkgo/ginkgo_87.npz', False),
    ('ginkgo/ginkgo_88.npz', True),
    ('ginkgo/ginkgo_89.npz', False),
    ('ginkgo/ginkgo_90.npz', False),
    ('ginkgo/ginkgo_91.npz', False),
    ('ginkgo/ginkgo_92.npz', False),
    ('ginkgo/ginkgo_93.npz', True),
    ('ginkgo/ginkgo_94.npz', False),
    ('ginkgo/ginkgo_95.npz', False),
    ('ginkgo/ginkgo_96.npz', False),
    ('ginkgo/ginkgo_97.npz', False),
    ('ginkgo/ginkgo_98.npz', False),
    ('ginkgo/ginkgo_99.npz', True),
    ('ginkgo/ginkgo_100.npz', False),
    ('pine/pine_1.npz', False),
    ('pine/pine_2.npz', True),
    ('pine/pine_3.npz', False),
    ('pine/pine_4.npz', False),
    ('pine/pine_5.npz', False),
    ('pine/pine_6.npz', False),
    ('pine/pine_7.npz', False),
    ('pine/pine_8.npz', False),
    ('pine/pine_9.npz', False),
    ('pine/pine_10.npz', False),
    ('pine/pine_11.npz', True),
    ('pine/pine_12.npz', False),
    ('pine/pine_13.npz', True),
    ('pine/pine_14.npz', False),
    ('pine/pine_15.npz', False),
    ('pine/pine_16.npz', False),
    ('pine/pine_17.npz', False),
    ('pine/pine_18.npz', False),
    ('pine/pine_19.npz', False),
    ('pine/pine_20.npz', False),
    ('pine/pine_21.npz', True),
    ('pine/pine_22.npz', False),
    ('pine/pine_23.npz', False),
    ('pine/pine_24.npz', False),
    ('pine/pine_25.npz', False),
    ('pine/pine_26.npz', False),
    ('pine/pine_27.npz', True),
    ('pine/pine_28.npz', False),
    ('pine/pine_29.npz', False),
    ('pine/pine_30.npz', True),
    ('pine/pine_31.npz', False),
    ('pine/pine_32.npz', False),
    ('pine/pine_33.npz', False),
    ('pine/pine_34.npz', False),
    ('pine/pine_35.npz', False),
    ('pine/pine_36.npz', False),
    ('pine/pine_37.npz', False),
    ('pine/pine_38.npz', False),
    ('pine/pine_39.npz', False),
    ('pine/pine_40.npz', False),
    ('pine/pine_41.npz', False),
    ('pine/pine_42.npz', False),
    ('pine/pine_43.npz', False),
    ('pine/pine_44.npz', False),
    ('pine/pine_45.npz', False),
    ('pine/pine_46.npz', True),
    ('pine/pine_47.npz', False),
    ('pine/pine_48.npz', False),
    ('pine/pine_49.npz', False),
    ('pine/pine_50.npz', False),
    ('pine/pine_51.npz', False),
    ('pine/pine_52.npz', True),
    ('pine/pine_53.npz', False),
    ('pine/pine_54.npz', False),
    ('pine/pine_55.npz', False),
    ('pine/pine_56.npz', False),
    ('pine/pine_57.npz', False),
    ('pine/pine_58.npz', False),
    ('pine/pine_59.npz', False),
    ('pine/pine_60.npz', False),
    ('pine/pine_61.npz', False),
    ('pine/pine_62.npz', False),
    ('pine/pine_63.npz', False),
    ('pine/pine_64.npz', False),
    ('pine/pine_65.npz', False),
    ('pine/pine_66.npz', False),
    ('pine/pine_67.npz', True),
    ('pine/pine_68.npz', False),
    ('pine/pine_69.npz', False),
    ('pine/pine_70.npz', False),
    ('pine/pine_71.npz', False),
    ('pine/pine_72.npz', False),
    ('pine/pine_73.npz', False),
    ('pine/pine_74.npz', False),
    ('pine/pine_75.npz', False),
    ('pine/pine_76.npz', True),
    ('pine/pine_77.npz', False),
    ('pine/pine_78.npz', False),
    ('pine/pine_79.npz', False),
    ('pine/pine_80.npz', False),
    ('pine/pine_81.npz', False),
    ('pine/pine_82.npz', False),
    ('pine/pine_83.npz', False),
    ('pine/pine_84.npz', False),
    ('pine/pine_85.npz', False),
    ('pine/pine_86.npz', False),
    ('pine/pine_87.npz', False),
    ('pine/pine_88.npz', False),
    ('pine/pine_89.npz', False),
    ('pine/pine_90.npz', False),
    ('pine/pine_91.npz', False),
    ('pine/pine_92.npz', False),
    ('pine/pine_93.npz', False),
    ('pine/pine_94.npz', False),
    ('pine/pine_95.npz', False),
    ('pine/pine_96.npz', False),
    ('pine/pine_97.npz', False),
    ('pine/pine_98.npz', False),
    ('pine/pine_99.npz', False),
    ('pine/pine_100.npz', False),
    ('walnut/walnut_1.npz', False),
    ('walnut/walnut_2.npz', True),
    ('walnut/walnut_3.npz', False),
    ('walnut/walnut_4.npz', False),
    ('walnut/walnut_5.npz', False),
    ('walnut/walnut_6.npz', False),
    ('walnut/walnut_7.npz', True),
    ('walnut/walnut_8.npz', False),
    ('walnut/walnut_9.npz', False),
    ('walnut/walnut_10.npz', False),
    ('walnut/walnut_11.npz', False),
    ('walnut/walnut_12.npz', True),
    ('walnut/walnut_13.npz', False),
    ('walnut/walnut_14.npz', False),
    ('walnut/walnut_15.npz', False),
    ('walnut/walnut_16.npz', False),
    ('walnut/walnut_17.npz', False),
    ('walnut/walnut_18.npz', False),
    ('walnut/walnut_19.npz', False),
    ('walnut/walnut_20.npz', False),
    ('walnut/walnut_21.npz', False),
    ('walnut/walnut_22.npz', False),
    ('walnut/walnut_23.npz', False),
    ('walnut/walnut_24.npz', False),
    ('walnut/walnut_25.npz', False),
    ('walnut/walnut_26.npz', True),
    ('walnut/walnut_27.npz', True),
    ('walnut/walnut_28.npz', False),
    ('walnut/walnut_29.npz', False),
    ('walnut/walnut_30.npz', False),
    ('walnut/walnut_31.npz', False),
    ('walnut/walnut_32.npz', False),
    ('walnut/walnut_33.npz', False),
    ('walnut/walnut_34.npz', False),
    ('walnut/walnut_35.npz', False),
    ('walnut/walnut_36.npz', False),
    ('walnut/walnut_37.npz', False),
    ('walnut/walnut_38.npz', False),
    ('walnut/walnut_39.npz', False),
    ('walnut/walnut_40.npz', False),
    ('walnut/walnut_41.npz', False),
    ('walnut/walnut_42.npz', False),
    ('walnut/walnut_43.npz', True),
    ('walnut/walnut_44.npz', False),
    ('walnut/walnut_45.npz', False),
    ('walnut/walnut_46.npz', False),
    ('walnut/walnut_47.npz', False),
    ('walnut/walnut_48.npz', False),
    ('walnut/walnut_49.npz', False),
    ('walnut/walnut_50.npz', False),
    ('walnut/walnut_51.npz', False),
    ('walnut/walnut_52.npz', False),
    ('walnut/walnut_53.npz', False),
    ('walnut/walnut_54.npz', False),
    ('walnut/walnut_55.npz', False),
    ('walnut/walnut_56.npz', False),
    ('walnut/walnut_57.npz', False),
    ('walnut/walnut_58.npz', False),
    ('walnut/walnut_59.npz', False),
    ('walnut/walnut_60.npz', False),
    ('walnut/walnut_61.npz', False),
    ('walnut/walnut_62.npz', False),
    ('walnut/walnut_63.npz', False),
    ('walnut/walnut_64.npz', False),
    ('walnut/walnut_65.npz', False),
    ('walnut/walnut_66.npz', True),
    ('walnut/walnut_67.npz', True),
    ('walnut/walnut_68.npz', False),
    ('walnut/walnut_69.npz', False),
    ('walnut/walnut_70.npz', False),
    ('walnut/walnut_71.npz', False),
    ('walnut/walnut_72.npz', False),
    ('walnut/walnut_73.npz', False),
    ('walnut/walnut_74.npz', False),
    ('walnut/walnut_75.npz', False),
    ('walnut/walnut_76.npz', False),
    ('walnut/walnut_77.npz', False),
    ('walnut/walnut_78.npz', False),
    ('walnut/walnut_79.npz', False),
    ('walnut/walnut_80.npz', False),
    ('walnut/walnut_81.npz', False),
    ('walnut/walnut_82.npz', False),
    ('walnut/walnut_83.npz', False),
    ('walnut/walnut_84.npz', False),
    ('walnut/walnut_85.npz', False),
    ('walnut/walnut_86.npz', False),
    ('walnut/walnut_87.npz', False),
    ('walnut/walnut_88.npz', False),
    ('walnut/walnut_89.npz', False),
    ('walnut/walnut_90.npz', False),
    ('walnut/walnut_91.npz', False),
    ('walnut/walnut_92.npz', True),
    ('walnut/walnut_93.npz', True),
    ('walnut/walnut_94.npz', False),
    ('walnut/walnut_95.npz', False),
    ('walnut/walnut_96.npz', False),
    ('walnut/walnut_97.npz', False),
    ('walnut/walnut_98.npz', False),
    ('walnut/walnut_99.npz', False),
    ('walnut/walnut_100.npz', False),
]

def evaluate_skeleton(
        gt_skeletal_points: np.ndarray,
        pred_skeletal_points: np.ndarray,
        *,
        gt_radii: Optional[np.ndarray] = None,
        pred_radii: Optional[np.ndarray] = None,
        pred_skeletal_edges: Union[None, np.ndarray, List[Tuple[int, int]]] = None,
        voxel_size: float = 0.01
) -> Dict[str, Any]:
    # Ground truth from Synthetic Tree dataset
    # It does not contain topology.
    metrics: Dict[str, Any] = {}

    # For each predicted skeletal point,
    # find the nearest one in the ground truth skeletal points as the True value.
    kdtree: KDTree = KDTree(gt_skeletal_points)
    neighbor_gt_skeletal_point_ids: np.ndarray = kdtree.query(pred_skeletal_points, k=1)[1]
    aligned_gt_skeletal_points: np.ndarray = gt_skeletal_points[neighbor_gt_skeletal_point_ids]
    pred_to_gt_distances: np.ndarray = np.linalg.norm(pred_skeletal_points - aligned_gt_skeletal_points, axis=1)
    metrics["N_points"] = len(pred_to_gt_distances)
    metrics["MAE_points"] = np.mean(pred_to_gt_distances)
    metrics["RMSE_points"] = np.sqrt(np.mean(pred_to_gt_distances ** 2))

    if gt_radii is not None:
        aligned_gt_radii: np.ndarray = gt_radii[neighbor_gt_skeletal_point_ids]
        differnce_from_pred_radii: np.ndarray = aligned_gt_radii - pred_radii
        metrics["MAE_r"] = np.mean(np.abs(differnce_from_pred_radii))
        metrics["MPE%_r"] = np.mean(differnce_from_pred_radii / (aligned_gt_radii + 1e-10)) * 100
        metrics["MAPE%_r"] = np.mean(np.abs(differnce_from_pred_radii / (aligned_gt_radii + 1e-10))) * 100
        metrics["sMAPE%_r"] = np.mean(np.abs(differnce_from_pred_radii) / (0.5 * (np.abs(aligned_gt_radii) + np.abs(pred_radii)) + 1e-10)) * 100
        metrics["RMSE_r"] = np.sqrt(np.mean(differnce_from_pred_radii ** 2))
        metrics["R2_r"] = r2_score(aligned_gt_radii, pred_radii)

    if pred_skeletal_edges is not None:
        # Generate dense sampling points from the predicted skeleton.
        sample_pred_skeletal_points: Union[List[np.ndarray], np.ndarray] = []

        for edge in pred_skeletal_edges:
            start_point: np.ndarray = pred_skeletal_points[edge[0]]
            end_point: np.ndarray = pred_skeletal_points[edge[1]]
            sample_pred_skeletal_points.append(sample_line_segment(start_point, end_point))

        sample_pred_skeletal_points = np.concatenate(sample_pred_skeletal_points, axis=0)

        # Use uniform bound
        combined_points: np.ndarray = np.concatenate([gt_skeletal_points, sample_pred_skeletal_points], axis=0)
        min_bound: np.ndarray = np.min(combined_points, axis=0)
        max_bound: np.ndarray = np.max(combined_points, axis=0)

        # Downsample to the same spatial density
        gt_cloud: Union[o3d.geometry.PointCloud, o3d.t.geometry.PointCloud] = o3d.geometry.PointCloud()
        pred_cloud: Union[o3d.geometry.PointCloud, o3d.t.geometry.PointCloud] = o3d.geometry.PointCloud()

        gt_cloud.points = o3d.utility.Vector3dVector(gt_skeletal_points)
        gt_cloud, _, _ = gt_cloud.voxel_down_sample_and_trace(voxel_size=voxel_size, min_bound=min_bound, max_bound=max_bound)
        pred_cloud.points = o3d.utility.Vector3dVector(sample_pred_skeletal_points)
        pred_cloud, _, _ = pred_cloud.voxel_down_sample_and_trace(voxel_size=voxel_size, min_bound=min_bound, max_bound=max_bound)

        gt_cloud = o3d.t.geometry.PointCloud.from_legacy(gt_cloud)
        pred_cloud = o3d.t.geometry.PointCloud.from_legacy(pred_cloud)

        cloud_metrics: np.ndarray = gt_cloud.compute_metrics(pred_cloud, (
            o3d.t.geometry.Metric.ChamferDistance,
        ), o3d.t.geometry.MetricParameters()).numpy()
        
        metrics["ChamferDistance"] = cloud_metrics[0]

    return metrics

def evaluate_on_synthetic_tree_dataset(
        fn_for_predicting_from_points: Callable[
            [np.ndarray], 
            Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray]]
        ],
        *,
        dataset_dir: str = "data/synthetic-trees",
        fully_tested: Union[bool, int, List[int]] = False,
        voxel_size: float = 0.01
) -> Dict[str, Dict[str, Any]]:
    test_files: List[str] = []
    if type(fully_tested) is int:
        test_files = [[file for file, _ in _synthetic_tree_files_with_selected][fully_tested]]
    elif type(fully_tested) is list:
        test_files = [file for i, file in enumerate([file for file, _ in _synthetic_tree_files_with_selected]) if i in fully_tested]
    elif fully_tested:
        test_files = [file for file, _ in _synthetic_tree_files_with_selected]
    else:
        test_files = [file for file, selected in _synthetic_tree_files_with_selected if selected]
    

    results: Dict[str, Dict[str, Any]] = {}

    for file in tqdm(test_files, desc="File", leave=False):
        try:
            file_path: str = os.path.join(dataset_dir, file)

            surface_points: np.ndarray
            displacements: np.ndarray
            with np.load(file_path) as f:
                surface_points = f['xyz']
                displacements = f['medial_vector' if 'medial_vector' in f.files else 'vector']

            # Coordinate transformation: X(-Z)Y -> XYZ
            surface_points[:, 2] = -surface_points[:, 2]
            surface_points[:, [0, 2, 1]] = surface_points[:, [0, 1, 2]]
            displacements[:, 2] = -displacements[:, 2]
            displacements[:, [0, 2, 1]] = displacements[:, [0, 1, 2]]

            gt_skeletal_points: np.ndarray = surface_points + displacements
            gt_radii: np.ndarray = np.linalg.norm(displacements, axis=1)

            pred_skeletal_points: np.ndarray
            pred_radii: Optional[np.ndarray]
            pred_skeletal_edges: Optional[np.ndarray]
            
            start_time: datetime = datetime.now()
            pred_skeletal_points, pred_radii, pred_skeletal_edges = fn_for_predicting_from_points(surface_points)
            end_time: datetime = datetime.now()

            metrics: Dict[str, float] = evaluate_skeleton(
                gt_skeletal_points=gt_skeletal_points, pred_skeletal_points=pred_skeletal_points, gt_radii=gt_radii, pred_radii=pred_radii, pred_skeletal_edges=pred_skeletal_edges, voxel_size=voxel_size
            )

            results[file] = metrics | {
                "cloud_size": len(surface_points),
                "duration(sec)": (end_time - start_time).total_seconds()
            }
        except Exception:
            error_msg: str = traceback.format_exc()
            results[file] = {"Error": error_msg}
            print(error_msg)
            print(f"Skipped {file}.")
        
    return results


def pipeline(
        sheet_name_to_fn_for_predicting_from_points: Dict[str, Callable[
            [np.ndarray], 
            Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray]]
        ]],
        saved_xlsx_filepath: str,
        *,
        dataset_dir: str = "data/synthetic-trees",
        fully_tested: Union[bool, int, List[int]] = False,
        voxel_size: float = 0.01
) -> None:
    sheet_name_to_tabular_dict: Dict[str, Dict[str, Dict[str, Any]]] = {}
    for sheet_name, fn_for_predicting_from_points in tqdm(sheet_name_to_fn_for_predicting_from_points.items(), desc="Item", leave=False):
        sheet_name_to_tabular_dict[sheet_name] = evaluate_on_synthetic_tree_dataset(
            fn_for_predicting_from_points,
            dataset_dir=dataset_dir,
            fully_tested=fully_tested,
            voxel_size=voxel_size
        )
        write_dicts_to_xlsx(sheet_name_to_tabular_dict, saved_xlsx_filepath)
        print(f"Saved {saved_xlsx_filepath}.")
    return