voxel_down_size: 0.01
filter: statistical_outlier_removal
kwargs_for_filter:
  nb_neighbors: 10
  std_ratio: 4.0
using_density_adaptation_in_skeletonization: True
skeletonization: 
  category: segmentation
  core_algorithm: layerwise_clustering
  core_algorithm_kwargs:
    max_patch_size: 0.04
    neighborhood_size: 0.055
    min_layer_height: 0.02
    max_layer_height: ~
    rough_height_diameter_ratio: 100
    stride_function: "lambda x, lb, ub: lb + x * (ub - lb)"
    cross_layer_cluster_spacing: 0.04
    flexible: False
    clustering_algorithm: dbscan
    clustering_algorithm_kwargs:
      eps: 0.04
      min_points: 5
    min_cluster_size: 5
  centroid_estimator: cpc
  params_for_centroid_estimator:
    bounded: True
  radius_estimator: gmm
  radius_estimator_kwargs:
    auto: True
    max_num_components: 2
  edge_search_kwargs: 
    r: 0.055
  edge_weight_function: l1
  topology_extractor: spt
refinement: 
  trusted_aboveground_height: 1.3
  trusted_height_ratio: 0.2
  min_radius_weight: !!float 1.0e-6
  x0_on_gamma_pdf: ~
  y0_on_gamma_pdf: ~
  wpl_based_correction_function_for_radius_weights: "lambda radius_weights, wpls: radius_weights * (np.log(wpls + 1.0) / np.log(np.max(wpls) + 1.0))"
  min_radius: !!float 1.0e-3
  occupancy_factor_or_buffer: 1.1
  smoother_kwargs:
    weight_fem_pos_deviation: !!float 1.0e10
    weight_path_length: 1.0
    weight_ref_deviation: 1.0
    bound: 0.055
  radius_tolerance: 0.0
  using_allometric_equation: False
  trunk_intercept_initval: 0.0
  trunk_intercept_minval: 0.0
  trunk_intercept_maxval : !!float 1.0e10
  lam_intercept_minval: 1.0
  lam_intercept_maxval: 100.0
  lam_intercept_tuning_function: "lambda wpl, wpl_max, lam_lb, lam_ub: (lam_lb / lam_ub) ** (np.log(wpl + 1.0) / np.log(wpl_max + 1.0)) * lam_ub"
  min_num_credible_samples: 5
  making_twigs_thinner: True
  node_weight_function: "lambda wpl, wpl_pred, r, r_pred: np.log(wpl + 1.0) / np.log(wpl_pred + 1.0) + r / r_pred"
modeling:
  num_sectional_vertices: 20
  using_furcation_optimization: True
  min_radius: !!float 1.0e-3
  resolution: 0.01
  range_multiplier: 2.75
  num_sectional_vertices_for_optimization: 12
  rdp_epsilon: 0.01
  num_hermite_nodes: 8